# Generated by Django 4.1 on 2022-08-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('dag', 'dag'), ('g', 'g'), ('pcs', 'pcs')], default='g', max_length=3),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('dag', 'dag'), ('g', 'g'), ('pcs', 'pcs')], default='g', max_length=3),
        ),
    ]
