# Generated by Django 4.1 on 2022-08-24 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredient_unit_alter_reciperequirement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
