# Generated by Django 4.1.1 on 2022-09-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_purchase_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirement',
            name='unit',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.TimeField(default='17:09:03'),
        ),
    ]
