# Generated by Django 4.1.1 on 2022-09-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_reciperequirement_unit_alter_purchase_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.TimeField(default='17:09:46'),
        ),
    ]
